### ISSUE TITLE
jar can not be load : com.r.tomcat.session.management.commons.SessionHandlerValve

### ISSUE THREAD

**Issue by wushuicheng** [ran-jit/TomcatRedisClusterEnabledSessionManager#1]
Sep 24, 2015 12:43:21 AM org.apache.tomcat.util.digester.Digester startElement
SEVERE: Begin event threw exception
java.lang.ClassNotFoundException: com.r.tomcat.session.management.commons.SessionHandlerValve
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:144)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1288)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1561)
        at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:649)
        at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:592)
        at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:850)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:397)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:110)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: invalid manifest format
        at java.util.jar.Manifest.read(Manifest.java:225)
        at java.util.jar.Manifest.<init>(Manifest.java:69)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:181)
        at java.util.jar.JarFile.getManifest(JarFile.java:167)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:779)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:416)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        ... 38 more

Sep 24, 2015 12:43:21 AM org.apache.catalina.startup.ContextConfig processContextConfig
SEVERE: Parse error in context.xml for /pay-web-boss
org.xml.sax.SAXParseException; systemId: file:/home/wusc/edu/web/boss-tomcat/conf/context.xml; lineNumber: 35; columnNumber: 86; Error at (35, 86) : com.r.tomcat.session.management.commons.SessionHandlerValve
        at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2711)
        at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2743)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1291)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1561)
        at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:649)
        at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:592)
        at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:850)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:397)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:110)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.r.tomcat.session.management.commons.SessionHandlerValve
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:144)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1288)
        ... 31 more
Caused by: java.io.IOException: invalid manifest format
        at java.util.jar.Manifest.read(Manifest.java:225)
        at java.util.jar.Manifest.<init>(Manifest.java:69)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:181)
        at java.util.jar.JarFile.getManifest(JarFile.java:167)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:779)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:416)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        ... 38 more

Sep 24, 2015 12:43:21 AM org.apache.catalina.startup.ContextConfig processContextConfig
SEVERE: Occurred at line 35 column 86
Sep 24, 2015 12:43:21 AM org.apache.catalina.startup.ContextConfig configureStart
SEVERE: Marking this application unavailable due to previous error(s)
Sep 24, 2015 12:43:21 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error getConfigured
Sep 24, 2015 12:43:21 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/pay-web-boss] startup failed due to previous errors
Sep 24, 2015 12:43:21 AM org.apache.catalina.startup.HostConfig deployWAR

**Comment by ran-jit** [comment]
Hi @wushuicheng 

Sorry for the late reply..

Have you tried with released jar..

https://github.com/ran-jit/TomcatRedisClusterEnabledSessionManager/releases/download/1.0/TomcatRedisSessionManager-1.0.zip

Kindly, update the jar in above mentioned URL and let me know the issue exists !!

**Comment by wushuicheng** [comment]
Hi Ranjith
Thanks for you reply！
I is using this version jar https://github.com/ran-jit/TomcatRedisClusterEnabledSessionManager/releases/download/1.0/TomcatRedisSessionManager-1.0.zip .

My application deploy environment is
CentOS 6.6_x64
1.7.0_72-b14
Tomcat 7.0.57

The exception logs is :
Sep 25, 2015 1:33:55 AM org.apache.catalina.core.StandardService startInternal 
INFO: Starting service Catalina 
Sep 25, 2015 1:33:55 AM org.apache.catalina.core.StandardEngine startInternal 
INFO: Starting Servlet Engine: Apache Tomcat/7.0.57 
Sep 25, 2015 1:33:55 AM org.apache.catalina.startup.HostConfig deployWAR 
INFO: Deploying web application archive /home/wusc/edu/web/boss-tomcat/webapps/pay-web-boss.war 
Sep 25, 2015 1:33:55 AM org.apache.tomcat.util.digester.Digester startElement 
SEVERE: Begin event threw exception 
java.lang.ClassNotFoundException: com.r.tomcat.session.management.commons.SessionHandlerValve 
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) 
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:358) 
at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:144) 
at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1288) 
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) 
at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182) 
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343) 
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786) 
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) 
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) 
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) 
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) 
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) 
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) 
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648) 
at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1561) 
at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:649) 
at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:592) 
at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:850) 
at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:397) 
at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117) 
at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) 
at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402) 
at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:110) 
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139) 
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) 
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) 
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649) 
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081) 
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 
at java.util.concurrent.FutureTask.run(FutureTask.java:262) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.io.IOException: invalid manifest format 
at java.util.jar.Manifest.read(Manifest.java:225) 
at java.util.jar.Manifest.<init>(Manifest.java:69) 
at java.util.jar.JarFile.getManifestFromReference(JarFile.java:181) 
at java.util.jar.JarFile.getManifest(JarFile.java:167) 
at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:779) 
at java.net.URLClassLoader.defineClass(URLClassLoader.java:416) 
at java.net.URLClassLoader.access$100(URLClassLoader.java:71) 
at java.net.URLClassLoader$1.run(URLClassLoader.java:361) 
... 38 more 

Sep 25, 2015 1:33:55 AM org.apache.catalina.startup.ContextConfig processContextConfig 
SEVERE: Parse error in context.xml for /pay-web-boss 
org.xml.sax.SAXParseException; systemId: file:/home/wusc/edu/web/boss-tomcat/conf/context.xml; lineNumber: 35; columnNumber: 87; Error at (35, 87) : com.r.tomcat.session.management.commons.SessionHandlerValve 
at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2711) 
at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2743) 
at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1291) 
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) 
at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182) 
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343) 
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786) 
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) 
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) 
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) 
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) 
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) 
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) 
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648) 
at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1561) 
at org.apache.catalina.startup.ContextConfig.processContextConfig(ContextConfig.java:649) 
at org.apache.catalina.startup.ContextConfig.contextConfig(ContextConfig.java:592) 
at org.apache.catalina.startup.ContextConfig.init(ContextConfig.java:850) 
at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:397) 
at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117) 
at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) 
at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402) 
at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:110) 
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139) 
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) 
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) 
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649) 
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081) 
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 
at java.util.concurrent.FutureTask.run(FutureTask.java:262) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.ClassNotFoundException: com.r.tomcat.session.management.commons.SessionHandlerValve 
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) 
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:358) 
at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:144) 
at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1288) 
... 31 more 
Caused by: java.io.IOException: invalid manifest format 
at java.util.jar.Manifest.read(Manifest.java:225) 
at java.util.jar.Manifest.<init>(Manifest.java:69) 
at java.util.jar.JarFile.getManifestFromReference(JarFile.java:181) 
at java.util.jar.JarFile.getManifest(JarFile.java:167) 
at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:779) 
at java.net.URLClassLoader.defineClass(URLClassLoader.java:416) 
at java.net.URLClassLoader.access$100(URLClassLoader.java:71) 
at java.net.URLClassLoader$1.run(URLClassLoader.java:361) 
... 38 more 

Sep 25, 2015 1:33:55 AM org.apache.catalina.startup.ContextConfig processContextConfig 
SEVERE: Occurred at line 35 column 87 
Sep 25, 2015 1:33:55 AM org.apache.catalina.startup.ContextConfig configureStart 
SEVERE: Marking this application unavailable due to previous error(s) 
Sep 25, 2015 1:33:55 AM org.apache.catalina.core.StandardContext startInternal 
SEVERE: Error getConfigured 
Sep 25, 2015 1:33:55 AM org.apache.catalina.core.StandardContext startInternal 
SEVERE: Context [/pay-web-boss] startup failed due to previous errors 
Sep 25, 2015 1:33:55 AM org.apache.catalina.startup.HostConfig deployWAR 
INFO: Deployment of web application archive /home/wusc/edu/web/boss-tomcat/webapps/pay-web-boss.war has finished in 805 ms 
Sep 25, 2015 1:33:55 AM org.apache.coyote.AbstractProtocol start 
INFO: Starting ProtocolHandler ["http-bio-8082"] 
Sep 25, 2015 1:33:55 AM org.apache.coyote.AbstractProtocol start 
INFO: Starting ProtocolHandler ["ajp-bio-8209"] 
Sep 25, 2015 1:33:55 AM org.apache.catalina.startup.Catalina start 
INFO: Server startup in 846 ms



I want to know where to set catalina.home="TOMCAT_LOCATION" ? 
in catalina.sh ? 
or in /etc/profile ?

Thank you very much !



吴水成
邮箱：wu-sc@foxmail.com
QQ：840765167（水到渠成）
 
From: Ranjith
Date: 2015-09-27 17:19
To: ran-jit/TomcatRedisClusterEnabledSessionManager
CC: wushuicheng
Subject: Re: [TomcatRedisClusterEnabledSessionManager] jar can not be load : com.r.tomcat.session.management.commons.SessionHandlerValve (#1)
Hi @wushuicheng 
Sorry for the late reply..
Have you tried with released jar..
https://github.com/ran-jit/TomcatRedisClusterEnabledSessionManager/releases/download/1.0/TomcatRedisSessionManager-1.0.zip
Kindly, update the jar in above mentioned URL and let me know the issue exists !!

**Comment by ran-jit** [comment]
Hello @wushuicheng 

The issue is because of the JAR file.

I have updated the same in below mentioned URL.
https://github.com/ran-jit/TomcatRedisClusterEnabledSessionManager/releases/download/1.0/TomcatRedisSessionManager-1.0.zip

Please update this in your end and check the same. I hope now its working fine @wushuicheng 

And reg: catalina.home property - For development environment we need to configure.

Kindly, let me know if in-case of any issues.

Thanks !!

**Comment by wushuicheng** [comment]
Hell Ranjith

I have update the jar file, but throw new exception:

2015-09-28 02:08:05,895 ERROR [CustomFilter.java:115] : == 
java.lang.NullPointerException 
at com.r.tomcat.session.management.redis.RedisSessionManager.createSession(RedisSessionManager.java:193) 
at org.apache.catalina.connector.Request.doGetSession(Request.java:2946) 
at org.apache.catalina.connector.Request.getSession(Request.java:2310) 
at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897) 
at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:909) 
at wusc.edu.pay.web.permission.filter.CustomFilter.doFilter(CustomFilter.java:98) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) 
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) 
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503) 
at com.r.tomcat.session.management.commons.SessionHandlerValve.invoke(SessionHandlerValve.java:28) 
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) 
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) 
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) 
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) 
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) 
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
at java.lang.Thread.run(Thread.java:745)


My project code , the red line throw exception:
public void doFilter(ServletRequest req, ServletResponse resp, FilterChain chain) throws IOException, ServletException { 
HttpServletRequest request = (HttpServletRequest) req; 
HttpServletResponse response = (HttpServletResponse) resp; 
String uri = request.getServletPath(); 

Object operator = request.getSession().getAttribute(PermissionConstant.OPERATOR_SESSION_KEY); 
if (!uri.startsWith("/login") && !uri.startsWith("/posTicket") && uri.endsWith(".action") && operator == null) { 
log.info("=======>url：" + uri); 
response.sendRedirect(request.getContextPath() + "/login_timeoutConfirm.action"); 
return; 
} 

chain.doFilter(xssRequest, response); 
return; 
} catch (RuntimeException e) { 
log.error("== ", e); 
getOutputMsg().put("STATE", "FAIL"); 
getOutputMsg().put("MSG", e.getMessage()); 
outPrint(response, JSONObject.fromObject(getOutputMsg())); 
} finally { 
ThreadLocalContext.remove(); 
} 
}



吴水成
邮箱：wu-sc@foxmail.com
手机：18926215592
QQ：840765167（水到渠成）
 
From: Ranjith
Date: 2015-09-28 01:49
To: ran-jit/TomcatRedisClusterEnabledSessionManager
CC: wushuicheng
Subject: Re: [TomcatRedisClusterEnabledSessionManager] jar can not be load : com.r.tomcat.session.management.commons.SessionHandlerValve (#1)
Hello @wushuicheng 
The issue is because of the JAR file.
I have updated the same in below mentioned URL.
https://github.com/ran-jit/TomcatRedisClusterEnabledSessionManager/releases/download/1.0/TomcatRedisSessionManager-1.0.zip
Please update this in your end and check the same. I hope now its working fine @wushuicheng 
And reg: catalina.home property - For development environment we need to configure.
Kindly, let me know if in-case of any issues.
Thanks !!

**Comment by wushuicheng** [comment]
My Redis3.0.3 Cluster configure is :
# redis hosts ex: 127.0.0.1:6379, 127.0.0.2:6379, 127.0.0.2:6380, .... 
redis.hosts=192.168.1.111:7111,192.168.1.112:7112,192.168.1.113:7113,192.168.1.114:7114,192.168.1.115:7115,192.168.1.116:7116
# Redis Password 
redis.password= 
# set true to enable redis cluster mode 
redis.cluster.enabled=true





吴水成
邮箱：wu-sc@foxmail.com
 
From: Ranjith
Date: 2015-09-28 01:49
To: ran-jit/TomcatRedisClusterEnabledSessionManager
CC: wushuicheng
Subject: Re: [TomcatRedisClusterEnabledSessionManager] jar can not be load : com.r.tomcat.session.management.commons.SessionHandlerValve (#1)
Hello @wushuicheng 
The issue is because of the JAR file.
I have updated the same in below mentioned URL.
https://github.com/ran-jit/TomcatRedisClusterEnabledSessionManager/releases/download/1.0/TomcatRedisSessionManager-1.0.zip
Please update this in your end and check the same. I hope now its working fine @wushuicheng 
And reg: catalina.home property - For development environment we need to configure.
Kindly, let me know if in-case of any issues.
Thanks !!

**Comment by ran-jit** [comment]
@wushuicheng 

It seems the redis connection not been established. so that causes this issue.

Have you checked the server startup logs. no errors ??

**Comment by ran-jit** [comment]
I suspect the issue is tomcat loads redis properties file which present inside the TomcatRedisSessionManager-1.0.jar

So, please modify the redis values in redis properties file which present inside the TomcatRedisSessionManager-1.0.jar and restart your tomcat server.

**Comment by wushuicheng** [comment]
I have modify redis.properties inside the TomcatRedisSessionManager-1.0.jar , But it's still the same problem




------------------ 原始邮件 ------------------
发件人: "Ranjith";<notifications@github.com>;
发送时间: 2015年9月28日(星期一) 凌晨2:45
收件人: "ran-jit/TomcatRedisClusterEnabledSessionManager"<TomcatRedisClusterEnabledSessionManager@noreply.github.com>; 
抄送: "水到渠成"<840765167@qq.com>; 
主题: Re: [TomcatRedisClusterEnabledSessionManager] jar can not be load :com.r.tomcat.session.management.commons.SessionHandlerValve (#1)




I suspect the issue is tomcat loads redis properties file which present inside the TomcatRedisSessionManager-1.0.jar
 
So, please modify the redis values in redis properties file which present inside the TomcatRedisSessionManager-1.0.jar and restart your tomcat server.

**Comment by ran-jit** [comment]
Hello @wushuicheng 

I have updated the JAR in below mentioned URL. https://github.com/ran-jit/TomcatRedisClusterEnabledSessionManager/releases/download/1.0/TomcatRedisSessionManager-1.0.zip

Please update this one and check the same.

Sorry !!

**Comment by wushuicheng** [comment]
int the com.r.data.cache.RedisClusterCacheUtils
I change the code "private boolean isClusterEnabled;" to "private boolean isClusterEnabled = true;"
so work well.
